#   Copyright 2012-2018 the original author or authors.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
openapi: "3.0.2"
info:
    version: "1.1"
    title: SFG Brewery API
    license:
        name: GNU GPLv3
        url: https://www.gnu.org/licenses/gpl.txt
    contact:
        name: John Thompson
        url: https://springframework.guru
servers:
    -   url: http://localhost:8080
        description: Local Host
tags:
    -   name: Beer
        description: Beer Operations
    -   name: Customer
        description: Customer Operations
    -   name: Order
        description: Order Operations
paths:
    /api/v1/beer:
        get:
            description: List Beers
            tags:
                - Beer
            parameters:
                - $ref: '#/components/parameters/Page'  
                - $ref: '#/components/parameters/PageSize'    
                - $ref: '#/components/parameters/BeerName'  
                - $ref: '#/components/parameters/BeerStyle'  
            responses:
                '200':
                    description: List Beers Response
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/BeerPagedList'
    /api/v1/beer/{beerId}:
        parameters:
            -   $ref: "#/components/parameters/BeerId"
        get:
            description: Get Beer by Id
            tags:
                - Beer
            responses:
                '200':
                    description: List Beers Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Beer'
                '404':
                    description: Not Found
    /api/v1/customers:
        post:
            description: Register as new customer
            tags:
                - Customer
            requestBody:
                required: false
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Customer"
            responses:
                '201':
                    description: Customer Created
                    headers:
                        Location:
                            description: Reference to created customer
                            schema:
                                type: string
                                format: uri                      
                '400':
                    description: Bad Request
    /api/v1/customers/{customerId}:
        parameters:
            -   $ref: "#/components/parameters/CustomerId"
        get:
            description: Get customer by Id
            tags:
                - Customer
            responses:
                '200':
                    description: HTTP Okay
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Customer"
                '404':
                    description: Not Found
    /api/v1/customers/{customerId}/creditcard:
        parameters:
            -   $ref: "#/components/parameters/CustomerId"
        get:
            description: List Customer's Credit Cards
            tags:
                - Customer
            parameters:
                - $ref: '#/components/parameters/Page'  
                - $ref: '#/components/parameters/PageSize'                 
            responses:
                '200':
                    description: List Credit Card Reponse
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/CreditCardPagedList"
        post:
            description: Create New Credit Card
            tags:
                - Customer
            responses:
                '201':
                    description: Credit Card Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditCard"
                    headers:
                        Location:
                            description: Reference to created credit card
                            schema:
                                type: string
                                format: uri        
                '400':
                    description: Bad Request
    /api/v1/customers/{customerId}/creditcard/{creditCardId}:
        parameters:
            -   $ref: "#/components/parameters/CustomerId"
            -   $ref: "#/components/parameters/CreditCardId"
        put:
            description: Create Credit Card
            tags:
                - Customer
            responses:
                '201':
                    description: Credit Card Created
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditCard"
                '400':
                    description: Bad Request
                '404':
                    description: Customer id or credit card id not found
        delete:
            description: Delete Credit Card
            tags:
                - Customer    
            responses:
                '200':
                    description: Credit Card Updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/CreditCard"
                '400':
                    description: Bad Request
                '404':
                    description: Customer id or credit card id not found
    /api/v1/customers/{customerId}/order:
        parameters:
            -   $ref: "#/components/parameters/CustomerId"
        get:
            description: List Orders
            tags:
                - Order
            responses:
                '200':
                    description: List Order Reponse
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/BeerOrderPagedList"
        post:
            description: Place Order
            tags:
                - Order
            requestBody:
                required: false
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BeerOrder"
            responses:
                '201':
                    description: Order Created
                    headers:
                        Location:
                            description: Reference to created Order
                            schema:
                                type: string
                                format: uri                      
                '404':
                    description: Not Found
            callbacks:
                orderStatusChange:
                    '{$request.body#/orderStatusCallback}':
                        description: Webhook post to reecive notifcations of order status changes.
                        post:
                            requestBody:
                                $ref: '#/components/requestBodies/OrderStatusCallback'
                            responses:
                                '200':
                                    description: Okay
    /api/v1/customers/{customerId}/order/{orderId}/pickup:
        parameters:
            -   $ref: "#/components/parameters/CustomerId"
            -   $ref: "#/components/parameters/OrderId"
        post:
            description: Pickup Order
            tags:
                - Order
            responses:
                '200':
                    description: HTTP Okay
                '404':
                    description: Customer Id or Order Id Not Found
components:
    parameters:
        BeerId:
            name: beerId
            in: path
            description: Beer Id
            required: true
            schema:
                type: string
                format: uuid
        BeerName:
            name: beerName
            in: query
            description: Beer Name
            required: false
            schema:
                type: string
        BeerStyle:
            name: beerStyle
            in: query
            description: Beer Style
            required: false
            schema:
                $ref: '#/components/schemas/BeerStyleEnum'
        CreditCardId:
            name: creditCardId
            in: path
            description: Credit Card Id
            required: true
            schema:
                type: string
                format: uuid
        CustomerId:
            name: customerId
            in: path
            description: Customer Id
            required: true
            schema:
                type: string
                format: uuid

        Page:
            name: pageNumber
            in: query
            description: Page number. 
            required: false
            schema:
                type: integer
                format: int32
                default: 1       
        PageSize:
            name: pageSize
            in: query
            description: Page size. 
            required: false
            schema:
                type: integer
                format: int32
                default: 25   
        OrderId:
            name: orderId
            in: path
            description: Order Id
            required: true
            schema:
                type: string
                format: uuid                      
    schemas:
        BaseItem:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                    readOnly: true
                version:
                    type: integer
                createdDate:
                    type: string
                    format: date-time
                lastModifiedDate:
                    type: string
                    format: date-time
        Beer:
            type: object
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            required:
                - beerName
                - beerStyle
                - quantityOnHand
                - price
            properties:
                beerName:
                    type: string
                beerStyle:
                    $ref: '#/components/schemas/BeerStyleEnum'
                quantityOnHand:
                    type: integer
                price:
                    type: string
                    format: decimal
        BeerPagedList:
            type: object
            allOf:
                - $ref: "#/components/schemas/PagedResponse"  
            properties:
                content:
                    type: array
                    items:
                        $ref: "#/components/schemas/Beer"              
        BeerOrder:
            type: object
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            properties:
                customerId:
                    type: string
                    format: uuid
                beerOrderLines:
                    type: array
                    items:
                        $ref: '#/components/schemas/BeerOrderLine'
                orderStatus:
                    $ref: "#/components/schemas/OrderStatusEnum"
                orderStatusCallbackUrl:
                    type: string
                    format: uri
        BeerOrderPagedList:
            type: object
            allOf:
                - $ref: "#/components/schemas/PagedResponse"  
            properties:
                content:
                    type: array
                    items:
                        $ref: "#/components/schemas/BeerOrder"                       
        BeerOrderLine:
            type: object
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            properties:
                beerId:
                    type: string
                    format: uuid
                quantity:
                    type: integer
                    minimum: 1
                    maximum: 999
        BeerStyleEnum:
            type: string
            enum:
                - LAGER
                - PILSNER
                - STOUT
                - GOSE
                - PORTER
                - ALE
                - WHEAT
                - IPA
                - PALE_ALE
                - SAISON            
        CreditCard:
            type: object
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            required:
                - cardNumber
                - expirationDate
                - cvv
                - primary
            properties:
                cardNumber:
                    type: integer
                expirationDate:
                    type: string
                    format: date
                cvv:
                    type: integer
                    maximum: 9999    
                primary:
                    type: boolean
                    default: true
                    description: Only One card can be set as primary
        CreditCardPagedList:
            type: object
            allOf:
                - $ref: "#/components/schemas/PagedResponse"  
            properties:
                content:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreditCard"                      
        Customer:
            type: object
            required:
                - name
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            properties:
                name:
                    type: string
                    maxLength: 255
                    minLength: 1
                creditCards:
                    type: array
                    items:
                        $ref: "#/components/schemas/CreditCard"
        PagedResponse:
            type: object
            properties:
                number:
                    type: integer
                    format: int32
                numberOfElements:
                    type: integer
                    format: int32
                totalPages:
                    type: integer
                    format: int32
                size:
                    type: integer
                    format: int32                
        OrderStatusEnum:
            type: string
            enum:
                - NEW
                - READY
                - PICKED_UP
        OrderStatusUpdate:
            type: object
            allOf:
                -   $ref: "#/components/schemas/BaseItem"
            properties:
                orderId:
                    type: string
                    format: uuid
                orderStatus:
                    $ref: "#/components/schemas/OrderStatusEnum"
    requestBodies:
        OrderStatusCallback:
            description: Order Status Update
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            orderId:
                                type: string
                                format: uuid
                            orderStatus:
                                $ref: "#/components/schemas/OrderStatusUpdate"